config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:new, :create, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, only: [:create, :edit, :update, :destroy],
              concerns: [:votable, :commentable], shallow: true do
      patch :accept, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy, as: :votable
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 10, maximum: 255 }
  validates :body, presence: true, length: { minimum: 10 }

  after_create_commit { QuestionsBroadcastJob.perform_later self }

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: [:show]

  authorize_resource

  def index
    respond_with Question.all
  end

  def show
    respond_with @question, serializer: SingleQuestionSerializer
  end

  def create
    respond_with @current_resource_owner.questions.create(question_params)
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: :show
  before_action :store_user_id, only: :show

  respond_to :html
  respond_to :js, only: [:edit, :update]

  authorize_resource

  def index
    respond_with(@questions = Question.includes(:user))
  end

  def new
    respond_with(@question = Question.new)
  end

  def show
    respond_with(@question)
  end

  def edit
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.new
  end

  def store_user_id
    gon.push({ current_user_id: current_user.id }) if user_signed_in?
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/views/questions/_form.html.slim
= render 'shared/errors_messages', resource: @question

.row
  .col-lg-6.col-md-8.col-sm-12
    = form_for @question do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'
      div
        = f.submit 'Add question', class: 'btn btn-primary'

app/views/questions/_form_create.html.slim
= render 'shared/errors_messages', resource: @question

.row
  .col-lg-6.col-md-8.col-sm-12
    = form_for @question do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'
      = render 'attachments/form_attachments', f: f
      div
        = f.submit 'Add question', class: 'btn btn-primary'

app/views/questions/_form_edit.html.slim
.question-form
  = render 'shared/errors_messages', resource: @question

  .row
    .col-lg-6.col-md-8.col-sm-12
      = form_for @question, remote: true do |f|
        .form-group
          = f.label :title
          = f.text_field :title, class: 'form-control'
        .form-group
          = f.label :body
          = f.text_area :body, class: 'form-control'
        = render 'attachments/form_attachments', f: f
        div
          = button_tag 'Cancel', type: 'button', class: 'btn btn-default cancel'
          = f.submit 'Update question', class: 'btn btn-primary'

app/views/questions/_question.html.slim
.item
  = render 'shared/signature', resource: question
  .item-body
    h4
      = link_to question.title, question
    div
      = question.body

app/views/questions/_question_view.html.slim
.item.question data-question-id="#{@question.id}"
  = render 'shared/signature', resource: @question
  .item-content.question-content
    .item-actions
      = render 'votes/vote', resource: @question
    h1= @question.title
    .item-body.question-body
      = simple_format(@question.body)
    = render 'shared/attachments', resource: @question
  = render 'comments/comments', resource: @question

app/views/questions/edit.js.erb
$('#edit-question-btn').off('ajax:success').on('ajax:success', function() {
    var $question = $('.question');

    $question.find('.question-content').hide().after('<%= j render 'questions/form_edit' %>');
    
    $question.on('click', '.cancel', function(e) {
        e.preventDefault();
        $(this).closest('.question-form').remove();
        $question.find('.question-content').show();
    });
});

app/views/questions/index.html.slim
h1 List of Questions
.row
  .col-sm-12
    = link_to 'Add question', new_question_path, class: 'btn btn-primary btn-lg pull-right', role: 'button'

.questions-list
  = render @questions

app/views/questions/new.html.slim
h1 Add question
= render 'form_create'

app/views/questions/show.html.slim
.row.button-bar
  .col-sm-12
    - if can?(:manage_own, @question)
      = link_to 'Delete', @question, method: :delete, class: 'btn btn-danger btn-sm pull-right',
              id: 'delete-question-btn', role: 'button'
      = link_to 'Edit', edit_question_path(@question), remote: true, class: 'btn btn-primary btn-sm pull-right',
              id: 'edit-question-btn', role: 'button'


= render 'questions/question_view'

h2 Answers:

.answers-list
  - if @question.answers.select(&:persisted?).any?
    = render @question.answers
  - else
    p class="empty-text" There is no answers yet.

- if can?(:create, Answer)
  = render 'answers/form_create'

app/views/questions/update.js.erb
var $form = $('#edit_question_<%= @question.id %>'),
    $alert = $form.find('.alert-danger');

$alert.remove();

<% if @question.errors.any? %>
    $form.prepend('<%= fix_remotipart { render 'shared/errors_messages', resource: @question } %>');
<% else %>
    $form.closest('.question').replaceWith('<%= fix_remotipart { render 'questions/question_view' } %>');
<% end %>