config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:new, :create, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, only: [:create, :edit, :update, :destroy],
              concerns: [:votable, :commentable], shallow: true do
      patch :accept, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  default_scope { order(accepted: :desc, created_at: :asc) }

  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
  validates :accepted, uniqueness: { scope: :question_id }, if: :accepted

  after_create_commit { AnswersBroadcastJob.perform_later self }

  scope :accepted, -> { where(accepted: true) }

  def accept
    transaction do
      question.answers.accepted.update_all(accepted: false)
      toggle(:accepted).save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :set_question, only: [:create]
  before_action :set_answer, only: [:edit, :update, :destroy, :accept]

  respond_to :js, only: [:edit, :update, :accept]
  respond_to :json, only: [:create, :destroy]

  authorize_resource

  def create
    respond_with(@question.answers.create(answer_params.merge(user: current_user)))
  end

  def edit
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def accept
    @answer.accept
    respond_with(@answer)
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_answer, only: [:show]
  before_action :set_question, only: [:index, :create]
  
  authorize_resource
  
  def index
    respond_with @question.answers
  end
  
  def show
    respond_with @answer, serializer: SingleAnswerSerializer
  end

  def create
    respond_with @question.answers.create(answer_params.merge(user: @current_resource_owner))
  end
  
  private
  
  def set_answer
    @answer = Answer.find(params[:id])
  end
  
  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_accept.html.slim
.answer-accepted
  - if can?(:accept, answer)
    = link_to accept_answer_path(answer), method: :patch, remote: true,
            class: "answer-accept accepted-#{answer.accepted ? 'on' : 'off'}" do
      = fa_icon 'check'

app/views/answers/_answer.html.slim
- if answer.persisted?
  .item.answer data-answer-id="#{answer.id}"
    .item-content.answer-content
      = render 'shared/signature', resource: answer

      .item-actions
        = render 'answers/accept', answer: answer
        = render 'votes/vote', resource: answer

      .item-body.answer-body
        - if can?(:manage_own, answer)
          .answer-buttons.pull-right
            = link_to 'Edit', edit_answer_path(answer), remote: true, class: 'answer-edit'
            | &nbsp;|&nbsp;
            = link_to 'Delete', answer_path(answer), method: :delete, remote: true,
                      data: { confirm: 'Are you sure?' }, class: 'answer-delete'
        div= simple_format(answer.body)
        = render 'shared/attachments', resource: answer
      = render 'comments/comments', resource: answer

app/views/answers/_form.html.slim
= render 'shared/errors_messages', resource: @answer
hr

.row
  .col-lg-6.col-md-8.col-sm-12
    = form_for [@question, @answer], remote: true do |f|
      .form-group
        = f.label :body, 'Add your answer:'
        = f.text_area :body, class: 'form-control'
      div
        = f.submit 'Add answer', class: 'btn btn-primary'

app/views/answers/_form_create.html.slim
= render 'shared/errors_messages', resource: @answer
<br>
.row
  .col-lg-6.col-md-8.col-sm-12
    = form_for [@question, @answer], remote: true do |f|
      .form-group
        = f.label :body, 'Add your answer:'
        = f.text_area :body, class: 'form-control'
      = render 'attachments/form_attachments', f: f
      div
        = f.submit 'Add answer', class: 'btn btn-primary'

app/views/answers/_form_edit.html.slim
.answer-form
  = render 'shared/errors_messages', resource: @answer

  .row
    .col-lg-6.col-md-8.col-sm-12
      = form_for @answer, remote: true do |f|
        .form-group
          = f.label :body, 'Add your answer:'
          = f.text_area :body, class: 'form-control'
        = render 'attachments/form_attachments', f: f
        div
          = button_tag 'Cancel', type: 'button', class: 'btn btn-default cancel'
          = f.submit 'Update answer', class: 'btn btn-primary'

app/views/answers/_vote.html.slim
.answer-vote
  - if user_signed_in? && current_user.author_of?(answer.question)
    = link_to accept_answer_path(answer), method: :patch, remote: true,
            class: "answer-accept accepted-#{answer.accepted ? 'on' : 'off'}" do
      = fa_icon 'check'

app/views/answers/accept.js.erb
$(document).off('ajax:success', '.answer-accept').on('ajax:success', '.answer-accept', function() {
    var $accepted_answer = $('.answer').has('.accepted-on'),
        $picked_answer = $(this).closest('.answer');

    $accepted_answer.find('.answer-accept').toggleClass('accepted-on accepted-off');
    $picked_answer.find('.answer-accepted').replaceWith('<%= render 'answers/accept', answer: @answer %>');
    $picked_answer.prependTo('.answers-list');
    });

app/views/answers/edit.js.erb
$(document).off('ajax:success', '.answer-edit').on('ajax:success', '.answer-edit', function() {
    var $answer = $(this).closest('.answer');
    
    $answer.append('<%= j render 'answers/form_edit' %>');
    $answer.find('.answer-content').hide();
    
    $answer.on('click', '.cancel', function(e) {
        e.preventDefault();
        $(this).closest('.answer-form').remove();
        $answer.find('.answer-content').show();
    });
});

app/views/answers/update.js.erb
var $form = $('#edit_answer_<%= @answer.id %>'),
    $alert = $form.find('.alert-danger');

$alert.remove();

<% if @answer.errors.any? %>
    $form.prepend('<%= fix_remotipart { render 'shared/errors_messages', resource: @answer } %>');
<% else %>
    $form.closest('.answer').replaceWith('<%= fix_remotipart { render @answer } %>');
<% end %>